services:
  server:
    container_name: bikehub_server
    depends_on:
      - database
    env_file: .env
    build:
      context: .
    networks:
      - default_network
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - .:/app
  database:
    container_name: "${DB_HOST}"
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - default_network
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    volumes:
      - bikehub_volume:/var/lib/postgresql/data
networks:
  default_network:
volumes:
  bikehub_volume:
